#Ingrid's Christmas Tree


print("                       /\                 ")
print("                      <  >                ")
print("                       \/                 ")
print("                       /\                 ")
print("                      /  \                ")
print("                     /    \               ")
print("                    /      \              ")
print("                   /        \             ")
print("                  /  *       \            ")
print("                 /         *  \           ")
print("                /              \          ")
print("               /       *        \         ")
print("              /                  \        ")
print("             /   *            *   \       ")
print("            /                      \       ")
print("           /  *             *       \       ")
print("          /         *                \       ")
print("         /                       *    \       ")
print("        /     *               *        \       ")
print("       /_____________       ____________\      ")
print("                    |       |                  ")
print("                    |       |                  ")
print("                    |_______|                  ")
